###

# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="testapiaudio1.mp3"
Content-Type: audio/mpeg

< ./test-files/testapiaudio1.mp3
--MfnBoundry--


###

# @name transcription
POST http://localhost:3333/videos/7c0df7e7-7f1d-4426-b6e4-8c7af90bbc90/transcription
Content-Type: application/json

{
    "prompt": "Video about the game baldur's gate 3"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/generate
Content-Type: application/json

{
    "videoId": "7c0df7e7-7f1d-4426-b6e4-8c7af90bbc90",
    "temperature": 0.8,
    "prompt": "IGN Article about Baldur's Gate 3: '''{transcription}'''"
}